name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: linux-amd64-cpu-1
    container:
      image: docker.m.daocloud.io/ubuntu:22.04
    steps:
      - name: Set up Python
        run: |
          # speed up by using infra cache services
          CACHING_URL="cache-service.nginx-pypi-cache.svc.cluster.local"
          sed -Ei "s@(ports|archive).ubuntu.com@${CACHING_URL}:8081@g" /etc/apt/sources.list
          apt update -y
          apt install -y python3.10 pip git
          pip config set global.extra-index-url "https://pypi.tuna.tsinghua.edu.cn/simple https://mirrors.aliyun.com/pypi/simple/"
          pip config set global.trusted-host "${CACHING_URL} pypi.tuna.tsinghua.edu.cn mirrors.aliyun.com"

      - name: Pre-config git access token
        run: |
          # as we use a proxy but checkout@v4 only set basic auth header for github.com
          # so we set the extraheader manually
          TOKEN=`echo -n "x-access-token:${{ secrets.ADMIN_PAT}}"|base64`
          git config --global http.https://gh-proxy.test.osinfra.cn/.extraheader "AUTHORIZATION: basic $TOKEN"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pre-commit hook
        run: |
          python3.10 -m pip install pre-commit
          git config --global --add safe.directory /__w/sglang/sglang
          pre-commit install

      - name: Linting
        run: pre-commit run --all-files --show-diff-on-failure
